package capaGrafica;



import javax.swing.JOptionPane;
import capaLogica.FachadaLogica;

/**
 *
 * @author octavio
 */
public class IngresoAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoAdmin.class.getName());

    /**
     * Creates new form IngresoAdmin
     */
    public IngresoAdmin() {
        initComponents();
    }
    
    private void limpiar() {
        passadmin.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingresoadmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passadmin = new javax.swing.JPasswordField();
        cedulaadmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula");

        jLabel2.setText("Contraseña");

        ingresoadmin.setText("Ingresar");
        ingresoadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoadminActionPerformed(evt);
            }
        });

        jLabel3.setText("INGRESO ADMINISTRADOR");

        passadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passadminActionPerformed(evt);
            }
        });

        cedulaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(ingresoadmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(cedulaadmin))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedulaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(ingresoadmin)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoadminActionPerformed

   try {
        int admin = Integer.parseInt(cedulaadmin.getText());

        String cedadmin = cedulaadmin.getText();
        
        FachadaLogica fachada = new FachadaLogica();

        if (cedadmin.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puede ingresar campos vacios.");
        }else {
            if(fachada.IniciarUs(admin)){
                JOptionPane.showMessageDialog(null, "Bienvenido");
                dispose();
                setVisible(false);
                InterfazDeEleccion inter =new InterfazDeEleccion();
                inter.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Cedula o Contraseña incorrecta ");
                limpiar();
            }
        }
        }catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al iniciar sesión: " + ex.getMessage());
        }
    }//GEN-LAST:event_ingresoadminActionPerformed

    private void passadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passadminActionPerformed

    private void cedulaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaadmin;
    private javax.swing.JButton ingresoadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passadmin;
    // End of variables declaration//GEN-END:variables
}
