/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGrafica;

import capaLogica.FachadaLogica;
import javax.swing.JOptionPane;


public class IngresoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoUsuario.class.getName());


    public IngresoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }
    //metodo para limpiar los textfield
    private void limpiar() {
        cedulausuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cedulausuario = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        botonloginadmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        jLabel1.setText("Cedula");

        cedulausuario.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        cedulausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulausuarioActionPerformed(evt);
            }
        });

        Ingresar.setFont(new java.awt.Font("Microsoft JhengHei", 3, 12)); // NOI18N
        Ingresar.setText("Ingresar");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        botonloginadmin.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        botonloginadmin.setText("Login Admin");
        botonloginadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonloginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonloginadminActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel3.setText("Unattendance-Register");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Ingresar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cedulausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonloginadmin)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulausuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(Ingresar)
                .addGap(18, 18, 18)
                .addComponent(botonloginadmin)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonloginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonloginadminActionPerformed
        setVisible(false);
        IngresoAdmin Admin = new IngresoAdmin();
        Admin.setVisible(true);
    }//GEN-LAST:event_botonloginadminActionPerformed

    
    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed

   try {
        //crea la variable usuario para parsearlo con int
        int usuario = Integer.parseInt(cedulausuario.getText());
        
        //crea otra variable con usuario para funciones de string
        String cedusuario = cedulausuario.getText();
        //aca verifica si lo que ingreso el usuario esta vacio
        if (cedusuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puede ingresar campos vacios.");
            
        }else {
            //llama a la clase fachada logica
            FachadaLogica fachada = new FachadaLogica();
            //ejecuta el metodo de fachada logica para iniciar sesion usuario y si es correcta accede a la tabla de datos
            if(fachada.IniciarUs(usuario)){
            dispose();
            setVisible(false);
            TablaDeDatos tabla =new TablaDeDatos();
            tabla.setVisible(true);
            }
            //si es falsa le da un mensaje al usuario
            else{
            JOptionPane.showMessageDialog(null, "La cedula que ingreso no es correcta, intentelo de nuevo mas tarde.");
            }
            //ejecuta el metodo limpiar para liberar los textfield
            limpiar();
        }
        //catch para manejo de excepciones
        }catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al iniciar sesión: " + ex.getMessage());
        //para mejores debugs muestra las excepciones en la consola para mejor entendimiento del error
        ex.printStackTrace();
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void cedulausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulausuarioActionPerformed
        
    }//GEN-LAST:event_cedulausuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton botonloginadmin;
    private javax.swing.JTextField cedulausuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
