package capaGrafica;

import javax.swing.JOptionPane;
import capaLogica.FachadaLogica;

/**
 *
 * @author octavio
 */
public class IngresoAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoAdmin.class.getName());

    /**
     * Creates new form IngresoAdmin
     */
    public IngresoAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    //metodo para limpiar textfields
    private void limpiar() {
        passadmin.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingresoadmin = new javax.swing.JButton();
        passadmin = new javax.swing.JPasswordField();
        cedulaadmin = new javax.swing.JTextField();
        atrasbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula");

        jLabel2.setText("Contraseña");

        ingresoadmin.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        ingresoadmin.setText("Ingresar");
        ingresoadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoadminActionPerformed(evt);
            }
        });

        passadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passadminActionPerformed(evt);
            }
        });

        cedulaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaadminActionPerformed(evt);
            }
        });

        atrasbtn.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        atrasbtn.setText("Atras");
        atrasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel4.setText("Ingreso para Administradores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingresoadmin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(cedulaadmin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(atrasbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedulaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ingresoadmin)
                .addGap(18, 18, 18)
                .addComponent(atrasbtn)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoadminActionPerformed

                                            
    try {
        //parsea los textfield
        String cedadmin = cedulaadmin.getText().trim();
        String contraadmin = passadmin.getText().trim();
        
        //valida
        if (cedadmin.isEmpty() || contraadmin.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puede ingresar campos vacíos.");
            return;
        }
        
        //valida que la cedula ingresada sea numerica
        try {
            Integer.parseInt(cedadmin);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cédula debe contener solo números.");
            return;
        }
        //llama a la fachada logica
        FachadaLogica fachada = new FachadaLogica();
        //inicio sesion verificando con el metodo sql
        if(fachada.IniciarAds(cedadmin, contraadmin)) {
            dispose();
            setVisible(false);
            InterfazDeEleccion inter = new InterfazDeEleccion();
            inter.setVisible(true);
            //ante error de typeo manda mensaje
        } else {
            JOptionPane.showMessageDialog(null, "Cédula o Contraseña incorrecta");
            limpiar();
        }
        //catch para manejo de excepciones
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al iniciar sesión: " + ex.getMessage());
        ex.printStackTrace(); //para debugear
    }

    }//GEN-LAST:event_ingresoadminActionPerformed

    private void passadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passadminActionPerformed

    private void cedulaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaadminActionPerformed

    private void atrasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasbtnActionPerformed
        dispose();
        setVisible(false);
        IngresoUsuario inus =new IngresoUsuario();
        inus.setVisible(true);
    }//GEN-LAST:event_atrasbtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasbtn;
    private javax.swing.JTextField cedulaadmin;
    private javax.swing.JButton ingresoadmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passadmin;
    // End of variables declaration//GEN-END:variables
}
