/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGrafica;

/**
 *
 * @author Pc
 */
public class InterfazDeEleccion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazDeEleccion.class.getName());

    /**
     * Creates new form InterfazDeEleccion
     */
    public InterfazDeEleccion() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrodeinasistencias = new javax.swing.JButton();
        registrousuario = new javax.swing.JButton();
        cierredesesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrodeinasistencias.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        registrodeinasistencias.setText("Registro de inasistencias docente");
        registrodeinasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeinasistenciasActionPerformed(evt);
            }
        });

        registrousuario.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        registrousuario.setText("Registro de usuario");
        registrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrousuarioActionPerformed(evt);
            }
        });

        cierredesesion.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        cierredesesion.setText("Cerrar sesion");
        cierredesesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierredesesionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel4.setText("Elija una de las opciones.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrodeinasistencias)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(registrousuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cierredesesion)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(registrodeinasistencias)
                .addGap(18, 18, 18)
                .addComponent(registrousuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(cierredesesion)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrodeinasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeinasistenciasActionPerformed
        dispose();
        setVisible(false);
        Registro regis =new Registro();
        regis.setVisible(true);   
    }//GEN-LAST:event_registrodeinasistenciasActionPerformed

    private void registrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrousuarioActionPerformed
        dispose();
        setVisible(false);
        RegistroDeNuevoUsuario regisnuevous =new RegistroDeNuevoUsuario();
        regisnuevous.setVisible(true);
    }//GEN-LAST:event_registrousuarioActionPerformed

    private void cierredesesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierredesesionActionPerformed
        dispose();
        setVisible(false);
        IngresoAdmin cierresesion =new IngresoAdmin();
        cierresesion.setVisible(true);
    }//GEN-LAST:event_cierredesesionActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cierredesesion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton registrodeinasistencias;
    private javax.swing.JButton registrousuario;
    // End of variables declaration//GEN-END:variables
}
