/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGrafica;

import javax.swing.JOptionPane;
import capaLogica.FachadaLogica;
import capaLogica.Usuario;

/**
 *
 * @author Pc
 */
public class RegistroDeNuevoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroDeNuevoUsuario.class.getName());


    public RegistroDeNuevoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    
    private void limpiar() {
        cedulanuevousuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registrarusuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cedulanuevousuario = new javax.swing.JTextField();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel1.setText("REGISTRO DE NUEVO USUARIO");

        registrarusuario.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        registrarusuario.setText("Registrar al usuario");
        registrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarusuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        jLabel2.setText("Cedula de nuevo usuario:");

        cedulanuevousuario.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N

        volver.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(cedulanuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(registrarusuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cedulanuevousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(registrarusuario)
                .addGap(29, 29, 29)
                .addComponent(volver)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarusuarioActionPerformed
        try {
        //convertir lo que ingreso el usuario en entero
        int usuario = Integer.parseInt(cedulanuevousuario.getText());
        
        //crea una variable para setear la cedula a string
        String cedulaus = cedulanuevousuario.getText();
        
        //verifica si los campos de textos estan vacios
        if (cedulaus.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos.");
            return;
        }
        
        //validacion para que solo acepte 8 numeros
        if (!cedulaus.matches("\\d+{8}")) {
            JOptionPane.showMessageDialog(null, "Error: La cedula solo puede contener 8 numeros.");
            limpiar();
            return;
        }        

        //llama fachada logica
        FachadaLogica fachada= new FachadaLogica();
        //llama al metodo login
        Usuario login = new Usuario();
        //setea lo que el usuario ingreso en el objeto cedula de usuario
        login.setCedula(usuario);
        //ejecuta funcion sql
        fachada.Registro(login);
        //confirma
        JOptionPane.showMessageDialog(null, "El nuevo usuario ha sido registrado exitosamente.");
        
        //catch para manejo de exceptions
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Error: La cédula debe contener solo números y máximo 8 dígitos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Ocurrio un error: " + ex.getMessage());
    }
        
        //limpia los campos de texto para cedula
        limpiar();
    }//GEN-LAST:event_registrarusuarioActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        setVisible(false);
        InterfazDeEleccion interelec =new InterfazDeEleccion();
        interelec.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    /**
     //* @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulanuevousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarusuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
